services:
  springboot-app:
    build:
      context: ../
      dockerfile: ./Dockerfile
    container_name: springboot-app
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    ports:
      - "8080:8080"
    networks:
      - mfa-app